<?php
$escape = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($this->translate('Persistent Identifiers'), 1, $this->translate('EZID Configuration')); ?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->escapeHtml($this->translate('Submit')); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php echo $this->form()->closeTag($form); ?>
