<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');

$filterLocale = false;
$lang = $this->lang();
?>

<?php if (isset($item)): ?>
<?php echo $this->pageTitle($item->displayTitle(null, ($filterLocale ? $lang : null)), 2); ?>
<h2><?php echo $translate('Item'); ?></h2>
<?php $this->trigger('view.show.before'); ?>
<?php
$itemMedia = $item->media();
if ($itemMedia):
?>
<div class="media-embeds">
    <?php foreach ($itemMedia as $media): ?>
        <div class="media-render"><?php echo $media->render(); ?></div>
    <?php endforeach; ?>
</div>
<?php endif; ?>
<h2><?php echo $translate('Metadata'); ?></h2>
<?php echo $item->displayValues(['viewName' => 'persistent-identifiers/common/pid-link-wrapper']); ?>
<?php if (isset($pid)): ?>
<h2><?php echo $translate('Persistent Identifier'); ?></h2>
<div class="pid">
    <div class="value"><?php echo $pid ?></div>
</div>
<?php endif; ?>
<?php
$itemSets = $item->itemSets();
if (count($itemSets) > 0):
?>
<div class="item-sets">
    <h2><?php echo $translate('Item sets'); ?></h2>
    <?php foreach ($itemSets as $itemSet): ?>
    <?php 
    $sites = $itemSet->sites();
    $setUrl = !empty($sites) ? $itemSet->siteUrl(array_values($sites)[0]->slug()) : null;
    ?>
    <div class="value">
        <?php if ($setUrl): ?><a href="<?php echo $escape($setUrl); ?>"><?php endif; ?>
        <?php echo $itemSet->displayTitle(null, ($filterLocale ? $lang : null)); ?>
        <?php if ($setUrl): ?></a><?php endif; ?>
    </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>
<?php if ($item->sites()): ?>
<h2><?php echo $translate('Sites'); ?></h2>
<div class="pid-site-list">
    <?php foreach ($item->sites() as $site): ?>
        <div class="site">
            <?php echo $this->hyperlink($site->title(), $item->siteUrl($site->slug()), ['class' => 'site-link']); ?>
        </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>
<?php if ($itemMedia): ?>
<h2><?php echo $translate('Media'); ?></h2>
<div class="media-list">
    <?php foreach ($itemMedia as $media): ?>
    <div class="value">
        <a href="<?php echo $escape($media->originalUrl() ?? $media->source()); ?>" class="resource-link">
            <?php echo $this->thumbnail($media, 'square'); ?>
            <span class="resource-name"><?php echo $escape($media->displayTitle()); ?></span>
        </a>
    </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>
<?php
$subjectValues = $item->displaySubjectValues([
        'page' => $this->params()->fromQuery('page', 1),
        'perPage' => 25,
        'resourceProperty' => $this->params()->fromQuery('resource_property'),
        'viewName' => 'persistent-identifiers/common/pid-link-wrapper',
    ])
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
    <h2><?php echo $translate('Linked resources'); ?></h2>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>
<?php $this->trigger('view.show.after'); ?>

<?php elseif (isset($invalidARK)): ?>
<?php echo $this->pageTitle($translate('Invalid Identifier'), 2); ?>
<div class="body">
    <?php echo sprintf(
        $translate('%1$s does not appear to be a valid ARK identifier.'),
        sprintf('<strong>%s</strong>', $escape($invalidARK))); ?>
</div>
<p>
    <?php echo $this->hyperlink($translate('Back to Home Page'), $this->url('top', ['action' => 'index'])) ?>
</p>

<?php elseif (isset($missingID)): ?>
<?php echo $this->pageTitle('Resource Removed', 2); ?>
<div class="body">
    <?php if (isset($pid)): ?>
    <?php echo sprintf(
        $translate('The resource with persistent identifier %1$s and local ID %2$s has been removed from this Omeka S instance.'),
        sprintf('<strong>%s</strong>', $pid),
        sprintf('<strong>%s</strong>', $missingID)); ?>
    <?php else: ?>
    <?php echo sprintf(
        $translate('The resource with local ID %1$s has been removed from this Omeka S instance.'),
        sprintf('<strong>%s</strong>', $missingID)); ?>
    <?php endif; ?>
</div>
<p>
    <?php echo $this->hyperlink($translate('Back to Home Page'), $this->url('top', ['action' => 'index'])) ?>
</p>
<?php endif; ?>
