<?php
$translate = $this->plugin('translate');
$escapeAttr = $this->plugin('escapeHtmlAttr');
$resourceTemplateSelect = $form->get('o:resource_template[o:id]');
$resourceClassSelect = $form->get('o:resource_class[o:id]');
$thumbnailInput = $form->get('o:thumbnail[o:id]');
$ownerSelect = $form->get('o:owner[o:id]');
if ($this->setting('pid_assign_all')) {
    $form->add([
                'name' => 'o:pid[o:id]',
                'type' => 'checkbox',
                'options' => [
                    'label' => 'Assign Persistent Identifier', // @translate
                    'info' => 'Mint & assign PID from chosen service.', // @translate
                ],
                'attributes' => [
		            'value' => true,
	            ],
            ]);
} else {
    $form->add([
                'name' => 'o:pid[o:id]',
                'type' => 'checkbox',
                'options' => [
                    'label' => 'Assign Persistent Identifier', // @translate
                    'info' => 'Mint & assign PID from chosen service.', // @translate
                ],
            ]);
};
$pid = $form->get('o:pid[o:id]');
if (isset($resource)) {
    if ($resourceTemplate = $resource->resourceTemplate()) {
        $resourceTemplateSelect->setValue($resourceTemplate->id());
    }
    if ($resourceClass = $resource->resourceClass()) {
        $resourceClassSelect->setValue($resourceClass->id());
    }
    if ($thumbnail = $resource->thumbnail()) {
        $thumbnailInput->setValue($thumbnail->id());
    }
    if ($owner = $resource->owner()) {
        $ownerSelect->setValue($owner->id());
    }
    // Pass Item API url to PID form for PID target
    $pid->setValue($resource);
} else {
    // Set the logged in user's default template when adding a resource.
    $resourceTemplateSelect->setValue($this->userSetting('default_resource_template'));
}
?>

<fieldset id="advanced-settings"
    class="section"
    aria-labelledby="advanced-settings-label">
    <?php echo $this->formRow($thumbnailInput); ?>
    <?php echo $this->formRow($pid); ?>
    <?php $this->trigger("view.$action.form.advanced", ['form' => $form]); ?>
</fieldset>
